/* Generated by Opal 0.6.3 */
(function($opal) {
  var self = $opal.top, $scope = $opal, nil = $opal.nil, $breaker = $opal.breaker, $slice = $opal.slice, $gvars = $opal.gvars, $klass = $opal.klass;

  $opal.add_stubs(['$new', '$eval', '$inspect', '$close_write', '$string', '$+', '$message', '$join', '$backtrace', '$__END__', '$innerHTML=', '$to_s', '$innerHTML', '$doc_element']);
  $opal.Object._proto.$exec_ruby = function(code) {
    var self = this, saved_stdout = nil, catcher = nil, res = nil, code_inspect = nil, code_output = nil, e = nil, code_error = nil;
    if ($gvars.stdout == null) $gvars.stdout = nil;

    saved_stdout = $gvars.stdout;
    try {
    try {
    catcher = $scope.StringIO.$new();
      $gvars.stdout = catcher;
      res = self.$eval(code);
      code_inspect = res.$inspect();
      catcher.$close_write();
      code_output = catcher.$string();
      
    console.log("inspect") 
    console.log(code)
    console.log( code_inspect )
    document.getElementById('code_output').innerHTML= 
    + code_output
    + "<br> = &gt;" 
    +  code_inspect
    ;
    } catch ($err) {if ($opal.$rescue($err, [$scope.Exception])) {e = $err;
      code_error = e.$message()['$+']("\n")['$+'](e.$backtrace().$join("\n"));
      
    console.log("error")
    console.log(code)
    console.warn(code_error)
    document.getElementById('code_output').innerHTML="<font size=\"3\" color=\"red\">" 
    +  code_error 
    + "</font>"
     ;
      }else { throw $err; }
    }
    } finally {
    $gvars.stdout = saved_stdout
    };
  };
  self.$__END__();
  return (function($base, $super) {
    function $FakeStdout(){};
    var self = $FakeStdout = $klass($base, $super, 'FakeStdout', $FakeStdout);

    var def = self._proto, $scope = self._scope;

    def.doc_element = nil;
    def.$initialize = function(doc_element) {
      var self = this;

      self.doc_element = document.getElementById(doc_element);
      return console.warn(self.doc_element);
    };

    def.$puts = function(thing) {
      var self = this;

      return self.doc_element['$innerHTML=']("" + (thing) + "\n");
    };

    def.$print = function(thing) {
      var self = this;

      return self.doc_element['$innerHTML=']("" + (thing));
    };

    def.$write = function(thing) {
      var self = this;

      return self.doc_element['$innerHTML='](thing.$to_s());
    };

    return (def['$<<'] = function(thing) {
      var self = this;

      return self.doc_element['$innerHTML='](self.$doc_element().$innerHTML()['$+'](thing));
    }, nil) && '<<';
  })(self, null);
})(Opal);
